name: ci

on:
  push:
  pull_request:

jobs:
  run-test:
    runs-on: macos-latest
    steps:
      - name: Get all system resource limits
        run: ulimit -a
      - name: Get socket buffer size
        run: sudo sysctl kern.ipc.maxsockbuf